### ISSUE TITLE
Any docs .. at all?

### ISSUE THREAD

**Issue by javadba** [gibiansky/python-pipes#1]
This is a concept for a library I WANT. Gotta get away from nested *for* comprehensions. But .. offer  *something* here.. example .. test .. something..

**Comment by gibiansky** [comment]
Not really, but there is a pretty long docstring [here](https://github.com/gibiansky/python-pipes/blob/master/pipes.py#L7) that explains the design and a few of the things the library provides. 

Also, the entire library is in `pipes.py`, so you can probably just read the entire file if you want all the details.

(This library was written for a job I was at a few years ago; we used it successfully internally for building some pretty long pipelines with several hundred commands. So it should work relatively well.)

Sorry -- hope that's enough to get you somewhere if you decide to use or fork the library!

**Comment by gibiansky** [comment]
I moved the info from `pipes.py` to the README.

**Comment by javadba** [comment]
thx for that quick response.  You might find the following SOF I just opened amusing   "Left to right application of operations on a list in python3"   https://stackoverflow.com/questions/49001986/left-to-right-application-of-operations-on-a-list-in-python3

I'll try to make something of this in the meantime.
